<<<<<<< HEAD
name: Production
=======
name: CI
>>>>>>> updated workflows

on:
  release:
    types: 
      - published

env:
  BUCKET_NAME: ${{ secrets.PRODUCTION_BUCKET_NAME }}
<<<<<<< HEAD
  DISTRIBUTION_ID: ${{ secrets.PRODUCTION_DISTRIBUTION_ID }}
=======
>>>>>>> updated workflows
  RUNNER_ROLE: ${{ secrets.EAD_PRODUCTION_RUNNER_ROLE }}
  RUNNER_EXTERNAL_ID: ${{ secrets.EAD_PROD_RUNNER_EXTERNAL_ID }}

jobs:
<<<<<<< HEAD
  Publish:
    
    runs-on: self-hosted

    if: ${{ github.repository }} == 'Alfresco/docs-alfresco'

=======
  jekyll-deploy:
    
    runs-on: self-hosted

>>>>>>> updated workflows
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run Jekyll Build
      uses: ./.github/actions/jekyll_build
    - name: Run S3 Sync
      uses: ./.github/actions/s3_sync