<<<<<<< HEAD
name: Sandbox

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - '.github/**'

env:
  BUCKET_NAME: ${{ secrets.SANDBOX_BUCKET_NAME }}
  DISTRIBUTION_ID: ${{ secrets.SANDBOX_DISTRIBUTION_ID }}
  RUNNER_ROLE: ${{ secrets.EAD_PRODUCTION_RUNNER_ROLE }}
  RUNNER_EXTERNAL_ID: ${{ secrets.EAD_PROD_RUNNER_EXTERNAL_ID }}

jobs:
  Publish:
    
    runs-on: self-hosted

    if: ${{ github.repository }} == 'Alfresco/docs-alfresco'

=======
name: CI

on:
  push:
    branches:
      - master

env:
  BUCKET_NAME: ${{ secrets.SANDBOX_BUCKET_NAME }}
  DISTRIBUTION_ID: ${{ secrets.SANDBOX_DISTRIBUTION_ID }}
  RUNNER_ROLE: ${{ secrets.EAD_PRODUCTION_RUNNER_ROLE }}
  RUNNER_EXTERNAL_ID: ${{ secrets.EAD_PROD_RUNNER_EXTERNAL_ID }}

jobs:
  jekyll-deploy:
    
    runs-on: self-hosted

>>>>>>> updated workflow
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run Jekyll Build
      uses: ./.github/actions/jekyll_build
    - name: Run S3 Sync
      uses: ./.github/actions/s3_sync