name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

env: 
  # AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  BUCKET_NAME: ${{ secrets.SANDBOX_BUCKET_NAME }}
  RUNNER_ROLE: ${{ secrets.EAD_PRODUCTION_RUNNER_ROLE }}

jobs:
  jekyll-deploy:
    
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # - name: Run Jekyll Build
    #   uses: ./.github/actions/jekyll_build
    - name: Run S3 Sync
      uses: ./.github/actions/s3_sync
    # - name: Run a one-line script
    #   run: echo Hello, world!
    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.