name: Staging

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

env:
  BUCKET_NAME: ${{ secrets.STAGING_BUCKET_NAME }}
  DISTRIBUTION_ID: ${{ secrets.STAGING_DISTRIBUTION_ID }}
  RUNNER_ROLE: ${{ secrets.EAD_PRODUCTION_RUNNER_ROLE }}
  RUNNER_EXTERNAL_ID: ${{ secrets.EAD_PROD_RUNNER_EXTERNAL_ID }}

jobs:
  Publish:
    
    runs-on: self-hosted

    if: ${{ github.repository }} == 'Alfresco/docs-alfresco'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run Jekyll Build
      uses: ./.github/actions/jekyll_build
      env:
        JEKYLL_CONFIG: _config.yml,_config.staging.yml
    - name: Run S3 Sync
      uses: ./.github/actions/s3_sync